[pytest]
# Where pytest should look for tests
testpaths = testcases
addopts = -v -s
# File patterns to consider as test files
python_files = test_*.py
# Minimum log level for pytest logs
log_cli = true